### ISSUE TITLE
Plugin does not install

### ISSUE THREAD

**Issue by geojochen** [chjch/pylusat-qgis#1]
This is the error message on QGIS 3.32:
Couldn't load plugin 'pylusat-qgis-main' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pylusat' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pylusat-qgis-main\__init__.py", line 37, in classFactory
    from .pylusatq_plugin import PyLUSATQProviderPlugin
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pylusat-qgis-main\pylusatq_plugin.py", line 38, in 
    from .pylusatq_provider import PyLUSATQProvider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pylusat-qgis-main\pylusatq_provider.py", line 35, in 
    from .algorithms.point_den import PointDensity
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joche/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pylusat-qgis-main\algorithms\point_den.py", line 12, in 
    from pylusat import base, density
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pylusat'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.2-Lima Lima, c0b8833964

**Comment by SabinaAsc** [comment]
I have the same error. Did you find any solution?

**Comment by rindra261** [comment]
I also have the same error with QGIS 3.34. How to solve it?
